name: ubuntu
on: 
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        mkdir outputs
        pwd
        ls -l
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - name: Test CernVM-FS
      run: |
        echo "### Dump default.local ###"
        cat /etc/cvmfs/default.local
        echo "### Test /cvmfs/cms.cern.ch ###"
        ls /cvmfs/cms.cern.ch
        echo "### /cvmfs/cms-opendata-conddb.cern.ch/ ###"
        ls /cvmfs/cms-opendata-conddb.cern.ch/
    - name: Run container
      run: |
        docker run -v $(pwd):/mnt/vol -v /cvmfs:/cvmfs:shared -w /home/cmsusr gitlab-registry.cern.ch/cms-cloud/cmssw-docker/slc5-cms:latest /bin/bash /mnt/vol/commands.sh 100000
        cp *.png outputs
  # upload output file
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: outputs/  
